---
become: true

env:
  - distribution: fedora
    version: rawhide
  - distribution: fedora
    version: latest
  - distribution: fedora
    version: 28

matrix:
  allow_failures:
    - env:
      - distribution: fedora
        version: rawhide

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/workstation_role:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/workstation_role/travis/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/workstation_role/travis/test.yml'
  - idempotence_test=$(sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/workstation_role/travis/test.yml)
  - >
    echo "${idempotence_test}" | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && echo "${idempotence_test}" && exit 1)
  - 'sudo docker rm -f "$(cat ${container_id})"'
