---
- name: Bash | Add the user 'nhenry'
  user:
    name: nhenry
    comment: Nick Henry
    groups:
      - docker
      - wheel
    home: /home/nhenry
    shell: /bin/bash

- name: Bash | Git Global Config
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: 'user.email', value: 'nshenry03@gmail.com' }
    - { name: 'user.name', value: 'Nick Henry' }
    - { name: 'user.signingkey', value: '4AFE58C3' }
  become: yes
  become_user: nhenry

- name: Bash | Creates 'Repositories' directory
  file:
    path: "/home/nhenry/Repositories/gists"
    state: directory
    mode: 0775
  become: yes
  become_user: nhenry

- name: Bash | Install bash gist
  git:
    repo: https://gist.github.com/6de76892df48cac6e8dfd543dad26412.git
    dest: "/home/nhenry/Repositories/gists/bash"
  become: yes
  become_user: nhenry

- name: Bash | Copy bash files into /home/nhenry
  copy:
    src: "/home/nhenry/Repositories/gists/bash/{{ item }}"
    dest: "/home/nhenry"
    mode: 0444
  with_items:
    - .bash_aliases
    - .bash_exports
    - .bash_profile
    - .bashrc
    - .inputrc
  become: yes
  become_user: nhenry

- name: Vim | Creates '.vim' directories
  file:
    path: "/home/nhenry/{{ item }}"
    state: directory
    mode: 0775
  with_items:
    - .vim
    - .vim.backupdir
    - .vim.swapdir
    - .vim/templates
  become: yes
  become_user: nhenry

- name: Vim | Install Vim Bash-Support
  unarchive:
    src: https://github.com/WolfgangMehner/bash-support/archive/version-4.3.tar.gz
    dest: "/home/nhenry/.vim"
    creates: "/home/nhenry/.vim/bash-support/README.md"
    remote_src: yes
    extra_opts:
      - --strip-components=1
    group: nhenry
    owner: nhenry

- name: Vim | Install Vim gist
  git:
    repo: https://gist.github.com/2b47d38c6837f26edc124c588989786a.git
    dest: "/home/nhenry/Repositories/gists/vim"
  become: yes
  become_user: nhenry

- name: Vim | Copy .vimrc into /home/nhenry
  copy:
    src: "/home/nhenry/Repositories/gists/vim/.vimrc"
    dest: "/home/nhenry"
    mode: 0444
  become: yes
  become_user: nhenry

- name: Vim | Copy vim personal.templates file into /home/nhenry
  copy:
    src: "/home/nhenry/Repositories/gists/vim/personal.templates"
    dest: "/home/nhenry/.vim/templates"
    mode: 0444
  become: yes
  become_user: nhenry
