---
- name: DNF | Install Basic Software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - ack
    - byobu
    - colordiff
    - gimp
    - gnome-tweak-tool
    - jq
    - meld
    - vim-enhanced
    - xclip

- name: DNF | Install DevOps Software
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - awscli

- name: DNF | Setup VirtualBox Repo
  get_url:
    url: http://download.virtualbox.org/virtualbox/rpm/fedora/virtualbox.repo
    dest: "/etc/yum.repos.d/virtualbox.repo"
    mode: 00644

- name: DNF | Install VirtualBox
  dnf:
    name: VirtualBox-5.2
    state: present

- name: DNF | Autoremove unneeded packages installed as dependencies
  dnf:
    autoremove: yes
