---
- hosts: all

  pre_tasks:
    - name: Ensure build dependencies are installed (RedHat)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - sudo
      when: ansible_os_family == 'RedHat'

  roles:
    - workstation_role
